apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kryptokrona-redis
  namespace: kryptokrona
spec:
  serviceName: kryptokrona-redis
  replicas: 1
  selector:
    matchLabels:
      app: kryptokrona-redis
  template:
    metadata:
      labels:
        app: kryptokrona-redis
    spec:
      initContainers:
      - name: config
        image: redis:6.2.3-alpine
        command: [ "sh", "-c" ]
        args:
          - |
            cp /tmp/redis/redis.conf /etc/redis/redis.conf
            
            echo "finding master..."
            MASTER_FDQN=`hostname  -f | sed -e 's/redis-[0-9]\./redis-0./'`
            if [ "$(redis-cli -h sentinel -p 5000 ping)" != "PONG" ]; then
              echo "master not found, defaulting to redis-0"

              if [ "$(hostname)" == "kryptokrona-redis-0" ]; then
                echo "this is redis-0, not updating config..."
              else
                echo "updating redis.conf..."
                echo "slaveof $MASTER_FDQN 6379" >> /etc/redis/redis.conf
              fi
            else
              echo "sentinel found, finding master"
              MASTER="$(redis-cli -h sentinel -p 5000 sentinel get-master-addr-by-name mymaster | grep -E '(^redis-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
              echo "master found : $MASTER, updating redis.conf"
              echo "slaveof $MASTER 6379" >> /etc/redis/redis.conf
            fi
        volumeMounts:
        - name: kryptokrona-redis-config
          mountPath: /etc/redis/
        - name: config
          mountPath: /tmp/redis/
      containers:
      - name: redis
        image: redis:6.2.3-alpine
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: kryptokrona-redis
          mountPath: /data
        - name: kryptokrona-redis-config
          mountPath: /etc/redis/
      volumes:
      - name: kryptokrona-redis-config
        emptyDir: {}
      - name: config
        configMap:
          name: kryptokrona-redis-config
  volumeClaimTemplates:
    - metadata:
        name: kryptokrona-redis
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: <STORAGECLASSNAME>
        resources:
          requests:
            storage: "1Gi"
