apiVersion: v1
kind: PersistentVolume
metadata:
  name: kryptokrona-redis
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  nfs:
    server: <YOUR IP OR FQDN>
    path: /path/to/the/magic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kryptokrona-redis
  namespace: kryptokrona
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: <STORAGECLASSNAME>